In [18]:
import numpy as np

In [19]:
x=np.array([34,12,7,89,1234,56,99,2])

In [22]:
# Standard Scaling using numpy
mean=np.mean(x)
s=np.std(x)
z=(x-mean)/s
print(np.round(z,3))

[-0.399 -0.454 -0.467 -0.259  2.636 -0.343 -0.234 -0.479]


In [23]:
# Min Max Scaling using numpy
minx=np.min(x)
maxx=np.max(x)
rangex=maxx-minx
m=(x-minx)/rangex
print(np.round(m,3))

[0.026 0.008 0.004 0.071 1.    0.044 0.079 0.   ]


In [33]:
# Standard Scaling using scikit-learn
from sklearn.preprocessing import StandardScaler
x=np.array([34,12,7,89,1234,56,99,2])
x2d=x.reshape(-1,1)
sc=StandardScaler()
sc.fit(x2d)
xtr=sc.transform(x2d)
xtr=xtr.ravel()
print(np.round(xtr,3))

[-0.399 -0.454 -0.467 -0.259  2.636 -0.343 -0.234 -0.479]


In [32]:
# Standard Scaling using scikit-learn
from sklearn.preprocessing import MinMaxScaler
x=np.array([34,12,7,89,1234,56,99,2])
x2d=x.reshape(-1,1)
sc=MinMaxScaler()
xtr=sc.fit_transform(x2d)
xtr=xtr.ravel()
print(np.round(xtr,3))

[0.026 0.008 0.004 0.071 1.    0.044 0.079 0.   ]


In [1]:
#import pandas
import pandas as pd
import numpy as np
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
# load dataset
pima = pd.read_csv("./data/diabetes.csv",names=col_names,header=0)

In [2]:
pima.head()

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1

In [3]:
X=pima[['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age']]
y=pima["label"]

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [5]:
np.round(X[:5,:],2)

array([[ 0.64,  0.85,  0.15,  0.91, -0.69,  0.2 ,  0.47,  1.43],
       [-0.84, -1.12, -0.16,  0.53, -0.69, -0.68, -0.37, -0.19],
       [ 1.23,  1.94, -0.26, -1.29, -0.69, -1.1 ,  0.6 , -0.11],
       [-0.84, -1.  , -0.16,  0.15,  0.12, -0.49, -0.92, -1.04],
       [-1.14,  0.5 , -1.5 ,  0.91,  0.77,  1.41,  5.48, -0.02]])